clc;
clear all;
close all;
 t=-15:.01:15;
 tm=10;
 fm=.1;
 x=2*sin(2*pi*fm*t);
 subplot(4,1,1);
 plot(t,x);
 xlabel('time');
 ylabel('amplitude');
 title('given sinusoidal signal');
 t1=-15:tm/100:15;
 y1=sin(2*pi*fm*t1);
 subplot(4,1,2);
 plot(t1,y1);
 xlabel('time');
 ylabel('amplitude');
 title('over-sampled signal');
 hold on;
 stem(t1,y1);
 hold off;
  t2=-15:tm/2:15;
 y2=sin(2*pi*fm*t2);
 subplot(4,1,3);
 plot(t2,y2);
 xlabel('time');
 ylabel('amplitude');
 title('critical-sampled signal');
 hold on;
 stem(t2,y2);
 hold off;
  t3=-15:tm/3:15;
 y3=sin(2*pi*fm*t3);
 subplot(4,1,4);
 plot(t3,y3);
 xlabel('time');
 ylabel('amplitude');
 title('under-sampled signal')
 hold on;
 stem(t3,y3);
 hold off;

